name: Build Extension

on:
  push:
    tags:
      - 'v*' # This will trigger on any tag that starts with 'v', like v0.1.1

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
      - name: Create build directory
        run: mkdir -p build
      
      - name: Copy extension files
        run: |
          cp ChatGptNavigator/manifest.json build/
          cp ChatGptNavigator/content.js build/
          cp ChatGptNavigator/styles.css build/
          cp -r ChatGptNavigator/images build/ || echo "No images directory found"
          cp ChatGptNavigator/LICENSE build/ || echo "No LICENSE file found"
          cp LICENSE build/ || echo "No root LICENSE file found"
      
      - name: Create ZIP archive
        run: |
          cd build
          zip -r ../chatgpt-navigator-${{ env.VERSION }}.zip .
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: chatgpt-navigator-${{ env.VERSION }}.zip
          draft: false
          prerelease: false
          name: ChatGPT Navigator v${{ env.VERSION }}
          body: |
            ChatGPT Navigator browser extension v${{ env.VERSION }}
            
            This extension adds a navigation panel to ChatGPT that shows links to all prompts.
          token: ${{ secrets.GITHUB_TOKEN }} 